baseurl: ''
url: 'https://gurcoff.com/'
name: Heladería GurCoff
author: Julian Franco
# email: info@enpitalito.com
whatsapp: https://wa.me/573115245225
tel: tel:+573115245225

permalink: /:categories/:title/

markdown: kramdown

keep_files: [/img]

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []