baseurl: ''
url: 'https://interconexiones.co/'
name: Interconexiones
author: Robinson Salazar
email: interconexionesmys@gmail.com
whatsapp: https://wa.me/573502517574
tel: tel:+573502517574

markdown: kramdown

keep_files: [/img]

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []